baseURL = "/"
locale = "en-US"
title = "Michael Novak"
theme = "noesis"
enableEmoji = true

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params]
  brand = "Michael Novak"
  description = "Michael Novak • Technologist"
  mainSections = ["posts"]

  [params.profile]
    jobTitle = "Engineer • Entrepreneur"
    location = "New York"
    headshotImage = "images/avatar.jpg"
    headshotAlt = "Michael Novak"

  [params.author]
    name = "Michael Novak"

  [params.socials]
    github = "https://github.com/novak/"
    x = "https://twitter.com/novak/"
    linkedin = "https://www.linkedin.com/in/michaelnovakjr/"
    mastodon = "https://hachyderm.io/@novak"
    calendar = "https://calendly.com/novakmichael/intro-meet-greet"

[markup]
  [markup.highlight]
    style = "evergarden"
